### ISSUE TITLE
More flexible RouteRegistrar ?

### ISSUE THREAD

**Issue by deem0n** [Wasappli/WAAppRouting#10]
Hello,

It seems that you must assign UIViewController for each and every path component.
It is ok when you control how URL is constructed, but I am working to handle existing Web links and they are quite cumbersome.

For example:
scheme://domain/#map/7b157902?a=b&c=d

where 7b157902 is actually a param, so it actually means scheme://domain/#map?guid=7b157902&a=b&c=d

I am trying to register with:

[registrar registerAppRoutePath:@"#map{MapViewController}/*" presentingController: nvc];

But I get error: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You need to have the class enclosed between {ClassName} on *'

[registrar registerAppRoutePath:@"#map/:guid{MapViewController}" presentingController: nvc];

result in: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You need to have the class enclosed between {ClassName} on #map'

I am going to subclass WAAppRouteRegistrar, but is there any better way to resolve it ?
Also I did not find documentation for :param notation. Is it only for numeric values ?

**Comment by ipodishima** [comment]
Hi there, sorry about the delay, just had some vacations

Well yeah, I'm not handling (yet) routes with path not mapped to a controller indeed.
This is on my roadmap though but I can't tell when I would develop and release it. Feel free to contribute if you have time to do so.

For the params, they are automatically handled for `?param1=value&param2=value2` and mapped to a dictionary and it's not just for numeric values.

**Comment by ivanyang1984** [comment]
i think it is easy to add an interceptor before you register your url.   which means you need transfer your url like this  path?query

**Comment by ipodishima** [comment]
@deem0n finally made it :)

`pod 'WAAppRouting', :git => 'https://github.com/Wasappli/WAAppRouting.git', :commit => 'ede0f90e5ff040eb77239d1f54253efe49785fb6'` waiting for 0.06 release once I'm sure it is working fine on my apps
