### ISSUE TITLE
iOS 7 compatibility

### ISSUE THREAD

**Issue by enfoiro** [Wasappli/WAAppRouting#12]
Hello,

You are using one method `string` from NSURLComponents [here](https://github.com/Wasappli/WAAppRouting/blob/master/Files/WAAppRouteMatcher.m#L19) introduced in iOS 8.0.
It leads to an unrecognised selector in iOS 7.0.

The `matchesURL` tries to match an url with a pattern twice, once with a scheme, and once without if the first one does not match.

I can't think of an example where we do need to match an url with its scheme.
I suggest that we only try to match urls without schemes.

If you agree with this, I could submit a PR.

**Comment by ipodishima** [comment]
Hi

Shit for the use of something not iOS 7 compatible...
To be honest, I cannot remember why I'm testing twice the url :/

**Comment by enfoiro** [comment]
Maybe you're testing twice to make a difference between a universal link and a custom scheme link.
But as we register routes without scheme, I don't know how an url with its scheme could possibly match a registered route.

I'm working with both universal links and custom scheme links and [this](https://github.com/enfoiro/WAAppRouting/commit/9c6770b9832e67cbb05fa20c02e76758222b0a0e) fix did the trick and both links still work well.
