### ISSUE TITLE
question about the url pattern path1/path2/path3

### ISSUE THREAD

**Issue by ivanyang1984** [Wasappli/WAAppRouting#14]
i saw the sample example with params demo .
 there is a code line  like     [self.router.registrar registerAppRoutePath:@"list{WAListViewController}/:articleID{WAListDetailViewController}/extra{WAListDetailExtraViewController}"
but i tried goto("list/3") crashed   why ？
although i didn't have kind of requirement like path1/path2 , i still wonder what is the purpose of design for path1/path2/path3...

**Comment by ivanyang1984** [comment]
[self goTo:@"simpleexampleparameters://list/3"];   i use this line instead of the original one [self goTo:@"simpleexampleparameters://list"];    crashed    get errors: 
reason: 'Application windows are expected to have a root view controller at the end of application launch'

**Comment by ivanyang1984** [comment]
i have read the code at all. i found it looks DSL design.   the stack management is some case extremely easy with push several relevant view controller in a stack and pop to previous relevant vc without setting a back item event.  but once i need to directly go to the page like "extra"， the page was pushed as a root vc, the list page not there.   if i want to put it upon the root vc , i will have to  
go to list1 first, then go to extra.
and the registration code will be like this:

```
[self.router.registrar registerAppRoutePath:@"list1{WAList1ViewController}"
                       presentingController:navigationControllerList1];

[self.router.registrar registerAppRoutePath:@"list1{WAList1ViewController}/:itemID{WAList1DetailViewController}"
                       presentingController:navigationControllerList1];

[self.router.registrar registerAppRoutePath:@"extra{WAList1DetailExtraViewController}"
                            presentingController:navigationControllerList1];
```

**Comment by ipodishima** [comment]
Hi

I'm not sure why `[self goTo:@"simpleexampleparameters://list/3"]` is crashing. Will have to check when I have time.
Usually, you do not open the app within a detail but rather to an home controller which would be `list`
Anyway, this should not crash.

I do not understand this part:

> although i didn't have kind of requirement like path1/path2 , i still wonder what is the purpose of design for path1/path2/path3...

If you need to go to extra, you have different options.
- First, let's say that extra is only available after `list1/:id`. You would register 

```
[self.router.registrar registerAppRoutePath:@"list1{WAList1ViewController}/:itemID{WAList1DetailViewController}/extra{ExtraVC}"
                       presentingController:navigationControllerList1];
```
- Second: extra is available as `list1/detail1/extra` but also `list1/extra`. You would then register two routes. In fact, each time you have possible subroutes, you have to register twice the path OR use the not sugar syntax (this syntax is just a wrapper around routes definition)
- Third option: access extra as a modal. Then, you would normally register your routes + 

```
[self.router.registrar registerAppRoutePath:@"extra{ExtraVC}!"
                            presentingController:navigationControllerList1];
```

Notice the `!` at the end, it means modal.

Hope I'm answering your questions

**Comment by ivanyang1984** [comment]
thanks for your reply,  i now can use your router handle any cases i had.  but i was still confused why you register  kind of path like "list1{WAList1ViewController}/:itemID{WAList1DetailViewController}/extra{ExtraVC}"  , once i push the extra,  there was a detail page under the extra,  if the user just click back will back to detail page instead of home page.  
what is the story of the design, i mean  why you try to design the router as a chain...push  1/2/3.... if i want to go 3, why not direct go 3, if i want to go "host?1/2/3",  each page will add the entry for next page, eg. in page 1, a button click let you go to 2, then 3 ...    on the other hand, what is the purpose of pushing  a bunch of pages?

**Comment by ipodishima** [comment]
Well this is all the purpose of this library actually. I was tired of others like deep link kit which only push the controller wherever we are on the stack. 

My need and why I designed it, is to be able, for example to go directly to an hotel booking but if I go back, I'm in the hotel detail and go back again I'm in the hotels list. 
This is all the purpose of an url actually, you have a path. 
If you are just looking for something to go to which means push view controller then this library won't be useful ;)

**Comment by ivanyang1984** [comment]
that looks so cool, i now can direct using the appLink.URL(list/detail/moreDetail---->that means the user go  list first, then detail , finally moreDetail ) as my  record of  the current page in user tracking.
