### ISSUE TITLE
how can i register my domain?

### ISSUE THREAD

**Issue by ivanyang1984** [Wasappli/WAAppRouting#15]
If i have an url like  http://www.ls.com/shopItemList.htm
the shopItemList.htm would like to mount to LSSShopItemListViewController 
how can i do the register?
now i write the code like below

``` objective-c
[self.router.registrar registerAppRoutePath:@"shopItemList{LSSShopItemListViewController}"
                           presentingController:[self.navigationControllerDic objectForKey:@"LSShopNavigationController"]]
```

it matches failed. then i drilled into your code, there was a separation operation will separate the m.ls.com and shopItemList  then you tried to company the count of path components 
like

``` objective-c
// If the count is not the same and there is no wildcard, no way this can match
    // Same if the route has less components than the pattern
    if (
        ([routePathComponents count] != [self.patternPathComponents count] && !self.patternHasWildcard)
        ||
        ([routePathComponents count] < [self.patternPathComponents count])
        ) {
        return NO;
    }
```

**Comment by ivanyang1984** [comment]
i found it, i just replace my domain to @""  then it works
like 

``` java
NSString *innerPath = [URL.absoluteString stringByReplacingOccurrencesOfString:@"m.ls.com/" withString:@""];
        handleUrl = [self.router handleURL:[NSURL URLWithString:innerPath]];
```

**Comment by ipodishima** [comment]
There is no such notion of a domain on the router. However, I might have some code to add in order to remove the domain from http[s] urls
