### ISSUE TITLE
transfer Object Param

### ISSUE THREAD

**Issue by jackyzonewen** [Wasappli/WAAppRouting#17]
AViewController container an tableview, the datasource is an Array Of AModel, When click one cell  enter BViewController, i wan't transfer the AModel Object to BViewController,How could i do? thanks

**Comment by ivanyang1984** [comment]
if there is a little quantity of params, you put those into queryParameters, that looks fine. but if your obj is large enough. you'd better make a datacenter for sharing those data in different pages.

**Comment by ivanyang1984** [comment]
i now met this problem, i decided to transfer the obj to json string, then urlEncode it .  when the next vc recieved, you need to decode the json string and deserialized to obj back.

**Comment by ipodishima** [comment]
Yes 

Or use any ID parameter you could use to fetch the object on your controllers
