### ISSUE TITLE
can you please support this?

### ISSUE THREAD

**Issue by ivanyang1984** [Wasappli/WAAppRouting#18]
i now have  a requirement that  i have a tab bar  , each bat item has its own navigation controller.
now i tried to register the same path such as home/orderlList/:orderId and myPage/orderList/:orderId , but failed. it said that i cannot have two entities with the same targetcontroller class.

i think it's quite reasonable when i have dynamic home with target url as home/orderList/:orderId   and i still have an origin orderDetail entry as myPage/orderList/:orderId .

i have tried to comment the nsassert , but seems got disorder of stack management.

**Comment by ivanyang1984** [comment]
i also tried your example with kinds of registration , saw it is not supported.

**Comment by ipodishima** [comment]
https://github.com/Wasappli/WAAppRouting/commit/795e095e61f34ee846424225a1cabe8291126d1e
