### ISSUE TITLE
if i design viewController's view by using storyboard,could i get viewControllers from WAAppRouting?

### ISSUE THREAD

**Issue by Neojoke** [Wasappli/WAAppRouting#24]

**Comment by ipodishima** [comment]
Nop, not at this moment :/

**Comment by mbjacks** [comment]
This can be achieved by subclassing WAApRouteHandler and overriding the `placeTargetViewControllerClass:inNavigationController:animated` method.  You can instantiate the view controller from storyboard with the storyboard identifier.  If you name all your storyboard id's after the class name, then you can just add:

`controllerToReturn = [navigationController.storyboard instantiateViewControllerWithIdentifier:NSStringFromClass(targetViewControllerClass)]`
